accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.list_book, name="book_list"),
    path('<int:book_id>/detail', views.book_detail, name="book_detail"),
    path('<int:book_id>/edit/', views.book_edit, name="book_edit"),
    path('<int:book_id>/delete/', views.book_delete, name='book_delete'),
    path('add/', views.Book_Add.as_view(), name='book_add'),
    path('book/<int:book_id>/like/', views.like, name='like'),

]

config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse


class Category(models.Model):
    # 本棚のモデル
    class Meta:
        db_table = 'category'

    name = models.CharField('カテゴリー名', max_length=50)

    def __str__(self):
        return self.name[:50]

# 本のモデル


class Book(models.Model):
    # テーブル名をbookにする
    class Meta:
        db_table = 'book'

    category = models.ForeignKey(Category, verbose_name='カテゴリー',
                                 on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField('本のタイトル', max_length=100)
    author = models.CharField('著者', max_length=100)
    recommend_level = models.IntegerField('おすすめレベル', default=1, validators=[
        MaxValueValidator(10), MinValueValidator(1)])
    recommend_context = models.TextField('おすすめポイント')
    date_posted = models.DateTimeField('投稿時間', auto_now=True)
    like = models.IntegerField(default=0)

    # 管理画面で、タイトルが表示されるようにする。
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book:book_list')

book/forms.py
from django import forms
from book.models import Book


class BookEditForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'category',
            'title',
            'author',
            'recommend_level',
            'recommend_context',

        )

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

book/views.py
from django.http import Http404, HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.core.paginator import Paginator

# データをJSON型に変換する
from django.core import serializers
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from django.views import generic

from .models import Book
from .forms import BookEditForm


def list_book(request):
    books = Book.objects.all()
    # いいねや編集後に順番が変わらないように本を登録した順(id順)に並び替える
    books = Book.objects.order_by('id')

    # 10冊を超えたら次のページを作る
    paginator = Paginator(books, 8)

    page = request.GET.get('page', 1)
    books = paginator.page(page)

    return TemplateResponse(request, 'book/index.html', {'books': books})


def book_detail(request, book_id):
    try:
        book = Book.objects.get(id=book_id)
    # 本が存在しない時はエラーメッセージを表示する
    except Book.DoesNotExist:
        raise Http404
    return TemplateResponse(request, 'book/book_detail.html', {'book': book})


def book_delete(request, book_id):
    try:
        book = Book.objects.get(id=book_id)

    # 本が存在しない時はエラーメッセージを表示する
    except Book.DoesNotExist:
        raise Http404

    # book_delete.htmlのformからデータが送られてきた時にそのデータを消す
    if request.method == 'POST':
        book.delete()
        return HttpResponseRedirect(reverse('book:book_list'))
    else:
        return TemplateResponse(request, 'book/book_delete.html', {'book': book})


def like(request, book_id):
    try:
        book = Book.objects.get(id=book_id)

    # 本が存在しない時はエラーメッセージを表示する
    except Book.DoesNotExist:
        raise Http404

    # この関数が呼び出された時にlikeに１を足して保存する
    book.like += 1
    book.save()

    book = get_object_or_404(Book, id=book_id)

    #book_like = serializers.serialize("json", book.like)

    return JsonResponse({"book_like": book.like, "book_id": book.id})


class Book_Add(generic.edit.CreateView):
    model = Book
    fields = '__all__'


def book_edit(request, book_id):
    try:
        book = Book.objects.get(id=book_id)
    # 本が存在しない時はエラーメッセージを表示する
    except Book.DoesNotExist:
        raise Http404

    # book_edit.htmlのformからデータが送られてきた時にそのデータを保存する
    if request.method == 'POST':
        form = BookEditForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            # 編集後はHome画面に戻る
            return HttpResponseRedirect(reverse('book:book_list'))

    else:
        form = BookEditForm(instance=book)
    # book_edit.htmlを呼び出す
    return TemplateResponse(request, 'book/book_edit.html',
                            {'form': form, 'book': book})

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Sign up</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Sign up</button>
    </form>
</section>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <link rel="icon" href="{% static '/images/favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!--Bootstrap-->
    <script data-ad-client="ca-pub-1976866996688533" async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <title>Recommend Book</title>
</head>

<body>
    <header class='site-header'>
        <nav class="navbar navbar-expand navbar-dark" style='background-color:#2d2d2d'>
            <ul class='navbar-nav mr-auto'>
                <li class=nav-item>
                    <a href="{% url 'book:book_list' %}" class='navbar-brand' style="margin-left: 15px;">Recommend
                        Book</a>
                </li>
            </ul>
            <ul class='navbar-nav'>
                <li class=nav-item>
                    <a href="{% url 'book:book_list' %}" class='nav-link'>Home</a>
                </li>
                <!--ログイン時にはログインしたユーザー名とLogoutを表示する-->
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'logout' %}" class='logout nav-link'>Logout</a>
                </li>
                <li class=nav-item>
                    <span class='navbar-text'>{{ user }}</span>
                </li>
                <!--ログインしていない時はLoginを表示する-->
                {% else %}
                <li class='nav-item'>
                    <a href="{% url 'login' %}" class='login nav-link'>Login</a>
                </li>

                <li class="nav-item">
                    <a href='{% url "accounts:signup" %}' class='signup nav-link'>Sign up</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main role='main' class='container-field'>
        <div style="margin-left: 25px; margin-right: 25px; margin-bottom: 0px; padding: 0px;">
        </div>
        {% block content %}{% endblock content %}

    </main>
    <footer id="footer" style="height: 150px; background-color: #2d2d2d;">
        <div style="text-align: center; color: #ffffff; padding-top: 70px;">Recommend Book</div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <!--twitter-->
    <script>
        window.twttr = (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0],
                t = window.twttr || {};
            if (d.getElementById(id)) return t;
            js = d.createElement(s);
            js.id = id;
            js.src = "https://platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js, fjs);

            t._e = [];
            t.ready = function (f) {
                t._e.push(f);
            };

            return t;
        }(document, "script", "twitter-wjs"));
    </script>
    <script type="text/javascript">
        amzn_assoc_ad_type = "link_enhancement_widget";
        amzn_assoc_tracking_id = "m2033099-22";
        amzn_assoc_linkid = "89836b116d919bbd9925cbb39b56aef7";
        amzn_assoc_placement = "";
        amzn_assoc_marketplace = "amazon";
        amzn_assoc_region = "JP";
    </script>
    <script
        src="//ws-fe.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1&MarketPlace=JP"></script>
    <script>
        new function () {

            var footerId = "footer";
            //メイン
            function footerFixed() {
                //ドキュメントの高さ
                var dh = document.getElementsByTagName("body")[0].clientHeight;
                //フッターのtopからの位置
                document.getElementById(footerId).style.top = "0px";
                var ft = document.getElementById(footerId).offsetTop;
                //フッターの高さ
                var fh = document.getElementById(footerId).offsetHeight;
                //ウィンドウの高さ
                if (window.innerHeight) {
                    var wh = window.innerHeight;
                } else if (document.documentElement && document.documentElement.clientHeight != 0) {
                    var wh = document.documentElement.clientHeight;
                }
                if (ft + fh < wh) {
                    document.getElementById(footerId).style.position = "relative";
                    document.getElementById(footerId).style.top = (wh - fh - ft - 1) + "px";
                }
            }

            //文字サイズ
            function checkFontSize(func) {

                //判定要素の追加	
                var e = document.createElement("div");
                var s = document.createTextNode("S");
                e.appendChild(s);
                e.style.visibility = "hidden"
                e.style.position = "absolute"
                e.style.top = "0"
                document.body.appendChild(e);
                var defHeight = e.offsetHeight;

                //判定関数
                function checkBoxSize() {
                    if (defHeight != e.offsetHeight) {
                        func();
                        defHeight = e.offsetHeight;
                    }
                }
                setInterval(checkBoxSize, 1000)
            }

            //イベントリスナー
            function addEvent(elm, listener, fn) {
                try {
                    elm.addEventListener(listener, fn, false);
                } catch (e) {
                    elm.attachEvent("on" + listener, fn);
                }
            }

            addEvent(window, "load", footerFixed);
            addEvent(window, "load", function () {
                checkFontSize(footerFixed);
            });
            addEvent(window, "resize", footerFixed);

        }
    </script>
</body>

</html>

templates/book/book_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h3>{{ book.title }}</h3>
<p>削除してもよろしいですか？</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="削除">
</form>

<a href="{% url 'book:book_list'%}">Homeに戻る</a>


{% endblock content %}

templates/book/book_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="変更">
</form>

<a href="{% url 'book:book_list' %}" class='btn btn-outline-primary'>Homeに戻る</a>

{% endblock content %}

templates/book/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
    .img {
        padding: 0px;
        margin: 0px;
        width: 100%;
    }

    .box {
        position: relative;
    }

    .box h1 {
        position: absolute;
        color: #ffffff;
        top: 125px;
        left: 50%;
    }

    .recommend {
        transform: translate(-50%, 0%);
    }

    .like {
        -webkit-appearance: none;
        position: relative;
        overflow: hidden;
        text-decoration: none;
        display: inline-block;
        background: #333;
        color: #ffffff;
        padding: 10px, 20px;
        border-radius: 25px;
        outline: none;
    }

    .like::after {
        content: "";
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        /* 波紋の形状 */
        background: radial-gradient(circle, #fff 10%, transparent 10%) no-repeat 50%;
        transform: scale(10, 10);
        /* はじめは透過0 */
        opacity: 0;
        /* アニメーションの設定 */
        transition: transform 0.3s, opacity 1s;
    }

    /* クリックされた後の形状の設定 */
    .like:active::after {
        transform: scale(0, 0);
        transition: 0s;
        opacity: 0.3;

    }
</style>
<div class="box">
    <img class="img" src="{% static 'images/books.jpg' %}"></img>
    <h1 class="recommend">おすすめの本を紹介しよう</h1>
</div>

<table class="table table-bordered table-striped">
    <thead class="thead-dark">
        <tr>
            <th class="text-center" style="width: 120px;">画像</th>
            <th class="text-center" style="width: 200px;">タイトル</th>
            <th class="text-center" style="width: 150px;">著者</th>
            <th class="text-center" style="width: 150px;">おすすめレベル</th>
            <th class="text-center" style="width: 120px;">いいね</th>
            <th class="text-center" style="width: 150px;"></th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <td class="text-center">
                {% if book.title == '独学プログラマー' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/B07BKVP9QY/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B07BKVP9QY&linkCode=as2&tag=m2033099-22&linkId=864f7db55ec287004d123d9e19cc0f37"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B07BKVP9QY&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == '君の膵臓をたべたい' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/B071RFTDZG/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B071RFTDZG&linkCode=as2&tag=m2033099-22&linkId=ce71bfd26eb1ff9cce28dcc0e4fee65d"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B071RFTDZG&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == '超集中力' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/B01FLFFF2Q/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B01FLFFF2Q&linkCode=as2&tag=m2033099-22&linkId=b60c0a574394eefef49fe573e2ffdb31"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B01FLFFF2Q&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == 'DUO' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/B07KY6Z241/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B07KY6Z241&linkCode=as2&tag=m2033099-22&linkId=779a7f65bb514433f45f609ddb133bd8"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B07KY6Z241&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == 'できるポケット HTML&CSS全辞典' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/4295008281/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=4295008281&linkCode=as2&tag=m2033099-22&linkId=51391a0e64d0c0f7d11030d51d70b0f4"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=4295008281&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == 'ストレスを力に変える教科書' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/B01D34LCY2/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B01D34LCY2&linkCode=as2&tag=m2033099-22&linkId=f3945ff247d663468d7204b419414239"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B01D34LCY2&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif '現場で使えるDjangoの教科書' in book.title %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/4802094744/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=4802094744&linkCode=as2&tag=m2033099-22&linkId=7b28dcc03770e305b65f30eff45b0c7a"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=4802094744&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == 'ゼロから作るDeep Learning' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/4873117585/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=4873117585&linkCode=as2&tag=m2033099-22&linkId=b6c32271b01f65de0ec4369667fbca2f"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=4873117585&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == 'アイデアのつくり方' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/4484881047/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=4484881047&linkCode=as2&tag=m2033099-22&linkId=c0bdf9a02c19ebeb3cb66bc9e78ee1e9"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=4484881047&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == 'ゼロ' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/B00G9KDQQU/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B00G9KDQQU&linkCode=as2&tag=m2033099-22&linkId=6fb0a4b402c19a60b667a30cdce8148c"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B00G9KDQQU&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% elif book.title == 'チーズはどこへ消えた？' %}
                <a target="_blank"
                    href="https://www.amazon.co.jp/gp/product/B00KD2IK4S/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B00KD2IK4S&linkCode=as2&tag=m2033099-22&linkId=3e9d20ac1e43bf5b5e9e4cfd81eac69a"><img
                        border="0"
                        src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B00KD2IK4S&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL110_&tag=m2033099-22"
                        class="img"></a>
                {% endif %}
            </td>
            <td class="text-center">{{ book.title }}</td>
            <td class="text-center">{{ book.author }}</td>
            <td class="text-center">{{ book.recommend_level }} / 10</td>
            <td class="text-center">

                <a href="javascript:void(0)" id="book_{{ book.id }}" name="{{ book.id }}" type="button"
                    class="like btn btn-primary" btn-primary value="いいね ({{ book.like }})">
                    いいね ({{ book.like }})</a>

            </td>
            <td class="text-center">
                <a href="{% url 'book:book_detail' book_id=book.id %}" class="btn btn-primary btn-sm"
                    style="margin-right: 8px;">詳細</a>
                <!--ログインしている時は削除ボタンを表示する-->
                {% if user.is_authenticated %}
                <a href="{% url 'book:book_delete' book_id=book.id %}" class="btn btn-secondary btn-sm"
                    style="margin-left: 8px;">削除</a>
                {% else %}
                <a href="{% url 'login' %}" class="btn btn-secondary btn-sm" style="margin-left: 8px;">削除</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>



</table>
<div style="float: left;">
    {% if books.has_previous %}
    <a href="?page={{ books.previous_page_number }}" class="btn btn-primary btn-sm">&lt; 前のページ</a>
    {% else %}
    <span>&lt; 前のページ</span>
    {% endif %}

    {{ books.number }}ページ

    {% if books.has_next %}
    <a href="?page={{ books.next_page_number }}" class="btn btn-primary btn-sm">次のページ &gt;</a>
    {% else %}
    <span>次のページ &gt;</span>
    {% endif %}
</div>
<div style="clear: both;"></div>
<div style="margin-bottom: 10px;"></div>

<!--ログインしている時は追加ボタンを表示する-->
{% if user.is_authenticated %}
<div style="margin-left: 60px; float: left;">
    <a href="{% url 'book:book_add' %}" class="btn btn-primary btn-sm">追加</a>
</div>
{% else %}
<div style="margin-left: 60px; float: left;">
    <a href="{% url 'login' %}" class="btn btn-primary btn-sm">追加</a>
</div>
{% endif %}
<div style="float: left; margin-left: 30px;">
    <!--tweetボタン-->
    <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=本を追加しました。#recommend_book">Tweet</a>
</div>
<div style="clear: both;"></div>
<div style="padding-bottom: 100px;"></div>

<script type="text/javascript">
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        crossDomain: false, // obviates need for sameOrigin test
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    //いいねボタンが押されたら非同期通信を行う
    $('.like').on('click', function () {
        var book_id = $(this).attr('name')

        $.ajax({
            type: 'POST',
            method: 'POST',
            url: book_id + '/like/',
            data: {
                'id': book_id
            },
            dataType: 'json'
        }).done(function (data) {
            $('#book_' + String(data['book_id'])).text('いいね ' + '(' + String(data['book_like']) + ')');
        })
    });

</script>


{% endblock content %}